name: deploy-frontend (dev)

on:
  push:
    branches: [dev]              # dev에서만 실행
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
  workflow_dispatch: {}          # 수동 실행 버튼

env:
  IMAGE: ${{ secrets.ACR_LOGIN_SERVER }}/yeahyak-frontend:dev

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (dev)
        uses: actions/checkout@v4
        with:
          # 푸시 이벤트면 해당 ref, 수동 실행이면 dev 고정
          ref: ${{ github.event_name == 'workflow_dispatch' && 'dev' || github.ref }}

      - name: Login ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build & Push image (dev)
        run: |
          set -e
          # Dockerfile 경로와 컨텍스트를 명시 (frontend/Dockerfile 존재 가정)
          docker build -t "$IMAGE" -f frontend/Dockerfile frontend
          docker push "$IMAGE"

      - name: Deploy to VM (frontend only)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script_stop: true
          script: |
            set -e
            cd /opt/yeahyak
            docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}

            # compose에 dev 이미지가 없으면 1회 치환
            grep -q 'yeahyak-frontend:dev' docker-compose.yml || \
              sed -i 's#nginxdemos/hello#${{ secrets.ACR_LOGIN_SERVER }}/yeahyak-frontend:dev#' docker-compose.yml

            docker compose pull frontend || true
            docker compose up -d --no-deps frontend
            docker image prune -f
